/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * User_Objectives.java
 *
 * Created on 15 juin 2011, 16:31:14
 */

package VisualAssistantFDM.userObjectives;

import java.awt.ComponentOrientation;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author Abdelheq
 */
public class User_Objectives extends javax.swing.JFrame {

    /** Creates new form User_Objectives */
    public User_Objectives(int row) {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("User Objectives"));
        jPanel1.setLayout(new java.awt.GridLayout(5, 5, 20, 50));

        JLabel labelObjective = new JLabel("Objective Name");
        JLabel labelImportance1 = new JLabel("Aucune Importance");
        JLabel labelImportance2 = new JLabel("Faible Importance");
        JLabel labelImportance3 = new JLabel("Moyenne Importance");
        JLabel labelImportance4 = new JLabel("Forte Importance");
        jPanel1.add(labelObjective);
        jPanel1.add(labelImportance1);
        jPanel1.add(labelImportance2);
        jPanel1.add(labelImportance3);
        jPanel1.add(labelImportance4);
        for(int i=2; i<=row; i++){
            JLabel labelObjectiveName = new JLabel("Objective "+i);
            JRadioButton RadioImportance1 = new JRadioButton();
            JRadioButton RadioImportance2 = new JRadioButton();
            JRadioButton RadioImportance3 = new JRadioButton();
            JRadioButton RadioImportance4 = new JRadioButton();
            jPanel1.add(labelObjectiveName);
            jPanel1.add(RadioImportance1);
            jPanel1.add(RadioImportance2);
            jPanel1.add(RadioImportance3);
            jPanel1.add(RadioImportance4);
        }

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new User_Objectives(row).setVisible(true);
                

                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
   private static int row = 5;
   //int row;
   //int column = 5;
}
